feat(songbox): update and add new features
- Updated workflows in `.github/workflows/update_ruleset.yml`
- Modified several JavaScript files in `htdocs/luci-static/resources/view/songbox/`
- Added new file `status.js` in `htdocs/luci-static/resources/view/songbox/`
- Updated configuration in `root/etc/config/songbox`
- Replaced `create_config.lua` with `create_config.uc` in `root/usr/libexec/rpcd/songbox/`
- Updated ACL configuration in `root/usr/share/rpcd/acl.d/luci-app-songbox.json`

diff --git a/.github/workflows/update_ruleset.yml b/.github/workflows/update_ruleset.yml
--- a/.github/workflows/update_ruleset.yml
+++ b/.github/workflows/update_ruleset.yml
@@ -21,8 +21,11 @@ jobs:
           curl -L $url | tar xz -C /tmp/
           sudo mv /tmp/sing-box-$(echo $version | sed 's/v//')-linux-amd64/sing-box /usr/local/bin/sing-box
           sing-box version
-          if [[ $? -eq 0 ]]; then
+          if [ $? -eq 0 ]; then
             echo "status=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "status=error" >> "$GITHUB_OUTPUT"
+          fi
 
       - name: Write Python script
         id: write-python-script
